"""Initial Tables

Revision ID: 9524a4d99814
Revises: 
Create Date: 2020-07-28 23:23:06.141674

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9524a4d99814'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('modules',
    sa.Column('id', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('agents_modules',
    sa.Column('id', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('agent_id', mysql.BIGINT(display_width=20), nullable=True),
    sa.Column('module_id', mysql.BIGINT(display_width=20), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_agents_modules_agent_id'), 'agents_modules', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agents_modules_module_id'), 'agents_modules', ['module_id'], unique=False)
    op.create_table('intents',
    sa.Column('id', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('module_id', mysql.BIGINT(display_width=20), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_intents_module_id'), 'intents', ['module_id'], unique=False)
    op.create_table('intent_contexts',
    sa.Column('id', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('intent_id', mysql.BIGINT(display_width=20), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['intent_id'], ['intents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_intent_contexts_intent_id'), 'intent_contexts', ['intent_id'], unique=False)
    op.create_table('intent_dialogs',
    sa.Column('id', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('intent_id', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('slot', sa.VARCHAR(length=255), nullable=True),
    sa.Column('input_type', sa.CHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['intent_id'], ['intents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intent_dialogs_intent_id'), 'intent_dialogs', ['intent_id'], unique=False)
    op.create_table('intent_patterns',
    sa.Column('id', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('intent_id', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['intent_id'], ['intents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_intent_patterns_intent_id'), 'intent_patterns', ['intent_id'], unique=False)
    op.create_table('intent_responses',
    sa.Column('id', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('intent_id', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['intent_id'], ['intents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intent_responses_intent_id'), 'intent_responses', ['intent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_intent_responses_intent_id'), table_name='intent_responses')
    op.drop_table('intent_responses')
    op.drop_index(op.f('ix_intent_patterns_intent_id'), table_name='intent_patterns')
    op.drop_table('intent_patterns')
    op.drop_index(op.f('ix_intent_dialogs_intent_id'), table_name='intent_dialogs')
    op.drop_table('intent_dialogs')
    op.drop_index(op.f('ix_intent_contexts_intent_id'), table_name='intent_contexts')
    op.drop_table('intent_contexts')
    op.drop_index(op.f('ix_intents_module_id'), table_name='intents')
    op.drop_table('intents')
    op.drop_index(op.f('ix_agents_modules_module_id'), table_name='agents_modules')
    op.drop_index(op.f('ix_agents_modules_agent_id'), table_name='agents_modules')
    op.drop_table('agents_modules')
    op.drop_table('modules')
    op.drop_table('agents')
    # ### end Alembic commands ###
