"""id Columns should be unique

Revision ID: c737241c3a15
Revises: 9524a4d99814
Create Date: 2020-08-11 20:02:42.812959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c737241c3a15'
down_revision = '9524a4d99814'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'agents', ['id'])
    op.create_unique_constraint(None, 'agents_modules', ['id'])
    op.create_unique_constraint(None, 'intent_contexts', ['id'])
    op.create_unique_constraint(None, 'intent_dialogs', ['id'])
    op.create_unique_constraint(None, 'intent_patterns', ['id'])
    op.create_unique_constraint(None, 'intent_responses', ['id'])
    op.create_unique_constraint(None, 'intents', ['id'])
    op.create_unique_constraint(None, 'modules', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'modules', type_='unique')
    op.drop_constraint(None, 'intents', type_='unique')
    op.drop_constraint(None, 'intent_responses', type_='unique')
    op.drop_constraint(None, 'intent_patterns', type_='unique')
    op.drop_constraint(None, 'intent_dialogs', type_='unique')
    op.drop_constraint(None, 'intent_contexts', type_='unique')
    op.drop_constraint(None, 'agents_modules', type_='unique')
    op.drop_constraint(None, 'agents', type_='unique')
    # ### end Alembic commands ###
